name: Build dev docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build dev docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git submodule init
        GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git submodule update --recursive
    - name: Build and push docker
      run: |
        export BUILD_ID=latest
        docker login -u=${{ secrets.DockerHubUsername }} -p=${{ secrets.DockerHubPassword }}
        docker build -t beisopss/keycloak:$BUILD_ID .
        docker push beisopss/keycloak:$BUILD_ID
